tier2:
  outputs:
    dev:
      database: awsdatacatalog
      region_name: ap-northeast-2
      s3_data_dir: s3:/{bucket_name}/tier2/
      s3_staging_dir: s3:/{bucket_name}/tier2/dbt/
      schema: tier2
      threads: 2
      type: athena
  target: dev